---

- name: Install the kerberos packages 
  apt: name={{ item }} state=present update_cache=yes
  register: install
  with_items: "{{ ubuntu_pkg }}"

- name: Copy the kdc configuration file 
  template: src=kdc.conf.j2 dest=/etc/krb5kdc/kdc.conf
  notify: restart kerberos ubuntu

- name: Link /dev/random to /dev/urandom
  file: path=/dev/random src=/dev/urandom state=link force=yes

- name: Copy the kdc acl configuration file 
  template: src=kadm5.acl.j2 dest=/etc/krb5kdc/kadm5.acl
  notify: restart kerberos ubuntu

- name: Copy the client configuration file 
  template: src=krb5.conf.j2 dest=/etc/krb5.conf

- name: Create the initial kerberos database
  script: create_db.sh {{ kerberos_master_db_pass }} 
  when: install.changed

- name: Make sure we have the entry for hostname in /etc/hosts  
  lineinfile: "path=/etc/hosts line='{{ ansible_default_ipv4.address }} {{ ansible_hostname }} {{ ansible_hostname + '.' + kerberos_realm_name|lower() }}'"

- name: Start the kerberos services 
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ubuntu_service}}"

- name: Create an admin for the administering the kerberos database
  script: create_admin.sh  {{ kerberos_kadmin_pass }} {{ kerberos_kadmin_user }} 
  when: install.changed

- name: Create kerberos users
  shell: echo -e "{{ item.pass }}\n{{ item.pass }}" | kadmin.local  -q "addprinc {{ item.user }}"
  with_items: "{{ kerberos_users }}"
  when: kerberos_users and install.changed
